-- CreateTable
CREATE TABLE `User` (
    `UserID` VARCHAR(191) NOT NULL,
    `Email` VARCHAR(191) NOT NULL,
    `Password` VARCHAR(191) NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT false,
    `Role` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `User_Email_key`(`Email`),
    PRIMARY KEY (`UserID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Address` (
    `AddressID` VARCHAR(191) NOT NULL,
    `Line` VARCHAR(191) NOT NULL,
    `City` VARCHAR(191) NOT NULL,
    `StateName` VARCHAR(191) NOT NULL,
    `Pincode` VARCHAR(191) NOT NULL,
    `UserId` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`AddressID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OrganizerDetail` (
    `OrganizerDetailID` VARCHAR(191) NOT NULL,
    `UserID` VARCHAR(191) NOT NULL,
    `FirstName` VARCHAR(191) NOT NULL,
    `LastName` VARCHAR(191) NOT NULL,
    `Phone` VARCHAR(191) NOT NULL,
    `Image` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`OrganizerDetailID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Trophy` (
    `TrophyID` VARCHAR(191) NOT NULL,
    `TrophyName` VARCHAR(191) NOT NULL,
    `OrganizerID` VARCHAR(191) NOT NULL,
    `StartDate` DATETIME(3) NOT NULL,
    `EndDate` DATETIME(3) NOT NULL,
    `Format` VARCHAR(191) NOT NULL,
    `Venue` VARCHAR(191) NOT NULL,
    `Image` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TrophyID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Team` (
    `TeamID` VARCHAR(191) NOT NULL,
    `TeamName` VARCHAR(191) NOT NULL,
    `Image` VARCHAR(191) NULL,
    `ShortName` VARCHAR(191) NOT NULL DEFAULT '',
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TeamID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Player` (
    `PlayerID` VARCHAR(191) NOT NULL,
    `FirstName` VARCHAR(191) NOT NULL,
    `LastName` VARCHAR(191) NOT NULL,
    `Phone` VARCHAR(191) NOT NULL,
    `DOB` DATETIME(3) NULL,
    `Role` VARCHAR(191) NULL,
    `BattingStyle` VARCHAR(191) NULL,
    `BowlingStyle` VARCHAR(191) NULL,
    `Image` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`PlayerID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TeamTrophy` (
    `TeamTrophyID` VARCHAR(191) NOT NULL,
    `TeamID` VARCHAR(191) NOT NULL,
    `TrophyID` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`TeamTrophyID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PlayerTeam` (
    `PlayerTeamID` VARCHAR(191) NOT NULL,
    `PlayerID` VARCHAR(191) NOT NULL,
    `TeamID` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`PlayerTeamID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Playing11` (
    `Playing11ID` VARCHAR(191) NOT NULL,
    `MatchID` VARCHAR(191) NOT NULL,
    `TeamID` VARCHAR(191) NOT NULL,
    `Wk` VARCHAR(191) NULL,
    `Cap` VARCHAR(191) NULL,
    `VCap` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Playing11ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Playing11Player` (
    `Playing11PlayerID` VARCHAR(191) NOT NULL,
    `PlayerID` VARCHAR(191) NOT NULL,
    `Playing11ID` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`Playing11PlayerID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Match` (
    `MatchID` VARCHAR(191) NOT NULL,
    `TrophyID` VARCHAR(191) NOT NULL,
    `Team1ID` VARCHAR(191) NOT NULL,
    `Team2ID` VARCHAR(191) NOT NULL,
    `MatchStatus` INTEGER NOT NULL DEFAULT 0,
    `MatchNumber` INTEGER NOT NULL,
    `TossWin` VARCHAR(191) NULL,
    `Choose` VARCHAR(191) NULL,
    `MatchTime` DATETIME(3) NULL,
    `MatchDate` DATETIME(3) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Ground` VARCHAR(191) NOT NULL DEFAULT '',
    `Result` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`MatchID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Innings` (
    `InningsID` VARCHAR(191) NOT NULL,
    `MatchID` VARCHAR(191) NOT NULL,
    `BattingTeamID` VARCHAR(191) NOT NULL,
    `BowlingTeamID` VARCHAR(191) NOT NULL,
    `TotalRuns` INTEGER NOT NULL,
    `TotalWickets` INTEGER NOT NULL,
    `WicketKeeperID` VARCHAR(191) NULL,
    `CurrOver` DOUBLE NOT NULL,
    `BatsmanStrikeId` VARCHAR(191) NOT NULL,
    `BatsmanNonStrikeId` VARCHAR(191) NOT NULL,
    `CurrBowlerId` VARCHAR(191) NOT NULL,
    `InningEnded` BOOLEAN NOT NULL DEFAULT false,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`InningsID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PlayerInning` (
    `PlayerInningID` VARCHAR(191) NOT NULL,
    `PlayerID` VARCHAR(191) NOT NULL,
    `InningsID` VARCHAR(191) NOT NULL,
    `Status` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`PlayerInningID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Scorecard` (
    `ScorecardID` VARCHAR(191) NOT NULL,
    `InningsID` VARCHAR(191) NOT NULL,
    `PlayerInningID` VARCHAR(191) NOT NULL,
    `RunsScored` INTEGER NOT NULL,
    `BallsFaced` INTEGER NOT NULL,
    `Sixes` INTEGER NOT NULL,
    `Fours` INTEGER NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ScorecardID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Out` (
    `OutID` VARCHAR(191) NOT NULL,
    `PlayerID` VARCHAR(191) NOT NULL,
    `InningID` VARCHAR(191) NOT NULL,
    `How` VARCHAR(191) NOT NULL,
    `BowlerID` VARCHAR(191) NULL,
    `ThrowerID` VARCHAR(191) NULL,
    `CatcherID` VARCHAR(191) NULL,
    `RunOuterID` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`OutID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Over` (
    `OverID` VARCHAR(191) NOT NULL,
    `InningsID` VARCHAR(191) NOT NULL,
    `BowlerID` VARCHAR(191) NOT NULL,
    `OverNumber` INTEGER NOT NULL,
    `MaidenOver` BOOLEAN NOT NULL DEFAULT false,
    `RunsConceded` INTEGER NOT NULL DEFAULT 0,
    `WicketsTaken` INTEGER NOT NULL DEFAULT 0,
    `Extras` INTEGER NOT NULL DEFAULT 0,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`OverID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Ball` (
    `BallID` VARCHAR(191) NOT NULL,
    `OverID` VARCHAR(191) NOT NULL,
    `BallNumber` INTEGER NOT NULL,
    `RunsScored` INTEGER NOT NULL,
    `WicketTaken` BOOLEAN NOT NULL DEFAULT false,
    `Extras` INTEGER NOT NULL,
    `key` VARCHAR(191) NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`BallID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Otp` (
    `OtpID` VARCHAR(191) NOT NULL,
    `UserID` VARCHAR(191) NOT NULL,
    `Code` VARCHAR(191) NOT NULL,
    `Expiry` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`OtpID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AdminLog` (
    `LogID` VARCHAR(191) NOT NULL,
    `UserID` VARCHAR(191) NOT NULL,
    `ActionDateTime` DATETIME(3) NOT NULL,
    `ActionDescription` VARCHAR(191) NOT NULL,
    `Created_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Updated_At` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`LogID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Address` ADD CONSTRAINT `Address_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`UserID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `OrganizerDetail` ADD CONSTRAINT `OrganizerDetail_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Trophy` ADD CONSTRAINT `Trophy_OrganizerID_fkey` FOREIGN KEY (`OrganizerID`) REFERENCES `User`(`UserID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TeamTrophy` ADD CONSTRAINT `TeamTrophy_TeamID_fkey` FOREIGN KEY (`TeamID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TeamTrophy` ADD CONSTRAINT `TeamTrophy_TrophyID_fkey` FOREIGN KEY (`TrophyID`) REFERENCES `Trophy`(`TrophyID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlayerTeam` ADD CONSTRAINT `PlayerTeam_PlayerID_fkey` FOREIGN KEY (`PlayerID`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlayerTeam` ADD CONSTRAINT `PlayerTeam_TeamID_fkey` FOREIGN KEY (`TeamID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Playing11` ADD CONSTRAINT `Playing11_MatchID_fkey` FOREIGN KEY (`MatchID`) REFERENCES `Match`(`MatchID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Playing11` ADD CONSTRAINT `Playing11_TeamID_fkey` FOREIGN KEY (`TeamID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Playing11Player` ADD CONSTRAINT `Playing11Player_PlayerID_fkey` FOREIGN KEY (`PlayerID`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Playing11Player` ADD CONSTRAINT `Playing11Player_Playing11ID_fkey` FOREIGN KEY (`Playing11ID`) REFERENCES `Playing11`(`Playing11ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Match` ADD CONSTRAINT `Match_TrophyID_fkey` FOREIGN KEY (`TrophyID`) REFERENCES `Trophy`(`TrophyID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Match` ADD CONSTRAINT `Match_Team1ID_fkey` FOREIGN KEY (`Team1ID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Match` ADD CONSTRAINT `Match_Team2ID_fkey` FOREIGN KEY (`Team2ID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_MatchID_fkey` FOREIGN KEY (`MatchID`) REFERENCES `Match`(`MatchID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_BattingTeamID_fkey` FOREIGN KEY (`BattingTeamID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_BowlingTeamID_fkey` FOREIGN KEY (`BowlingTeamID`) REFERENCES `Team`(`TeamID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_BatsmanStrikeId_fkey` FOREIGN KEY (`BatsmanStrikeId`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_BatsmanNonStrikeId_fkey` FOREIGN KEY (`BatsmanNonStrikeId`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Innings` ADD CONSTRAINT `Innings_CurrBowlerId_fkey` FOREIGN KEY (`CurrBowlerId`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlayerInning` ADD CONSTRAINT `PlayerInning_PlayerID_fkey` FOREIGN KEY (`PlayerID`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PlayerInning` ADD CONSTRAINT `PlayerInning_InningsID_fkey` FOREIGN KEY (`InningsID`) REFERENCES `Innings`(`InningsID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Scorecard` ADD CONSTRAINT `Scorecard_InningsID_fkey` FOREIGN KEY (`InningsID`) REFERENCES `Innings`(`InningsID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Scorecard` ADD CONSTRAINT `Scorecard_PlayerInningID_fkey` FOREIGN KEY (`PlayerInningID`) REFERENCES `PlayerInning`(`PlayerInningID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Out` ADD CONSTRAINT `Out_PlayerID_fkey` FOREIGN KEY (`PlayerID`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Out` ADD CONSTRAINT `Out_InningID_fkey` FOREIGN KEY (`InningID`) REFERENCES `Innings`(`InningsID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Over` ADD CONSTRAINT `Over_InningsID_fkey` FOREIGN KEY (`InningsID`) REFERENCES `Innings`(`InningsID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Over` ADD CONSTRAINT `Over_BowlerID_fkey` FOREIGN KEY (`BowlerID`) REFERENCES `Player`(`PlayerID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Ball` ADD CONSTRAINT `Ball_OverID_fkey` FOREIGN KEY (`OverID`) REFERENCES `Over`(`OverID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Otp` ADD CONSTRAINT `Otp_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AdminLog` ADD CONSTRAINT `AdminLog_UserID_fkey` FOREIGN KEY (`UserID`) REFERENCES `User`(`UserID`) ON DELETE RESTRICT ON UPDATE CASCADE;
